GET http://localhost:5000

###

GET http://localhost:5000/api/auth

###
GET http://localhost:5000/api/watching
###
GET http://localhost:5000/api/favorite

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "tuan",
  "firstname": "tuan",
  "lastname": "nguyen"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nguyentuan200422@gmail.com",
  "password": "tuan"
}

###

GET http://localhost:5000/api/watching
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjIyNDMwMzcsImV4cCI6MTcyMjI0MzMzN30.NKp5DN7dcnzeRveGbfuMJB4mEDBMPOSqyursHzc05iw

###

PUT http://localhost:5000/api/watching
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjIzNjk4MDEsImV4cCI6MTcyMjM3MDEwMX0.Le5JAqcoTbMq1kzGy-lKEL-GoeI_DSwF-CJO1Z00AXs

{
  "films":   [
    {
      "id": 1,
      "quantity": 2,
      "size": "S"
    },
    {
      "id": 2,
      "quantity": 2,
      "size": "S"
    },
    {
      "id": 4,
      "quantity": 11,
      "size": "S"
    }
  ]
}

###

GET http://localhost:5000/api/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjIyNDk4OTksImV4cCI6MTcyMjI1MDE5OX0.F_-XOCBF5N77fIbA2EqwOjeTHczOA21MnV8CuA0z54g

###

PUT http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjIzNzA2MzQsImV4cCI6MTcyMjQ1NzAzNH0.NyNRce92y14Hq6OjiflweIZ5ckT5d-xoEOHumflX3YA

{
  "films":   [
    {
      "_id": 1,
      "quantity": 2,
      "size": "S"
    },
    {
      "_id": 2,
      "quantity": 2,
      "size": "S"
    },
    {
      "_id": 4,
      "quantity": 11,
      "size": "S"
    }
  ]
}

###

PUT http://localhost:5000/api/favorite/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjIzNzA2MzQsImV4cCI6MTcyMjQ1NzAzNH0.NyNRce92y14Hq6OjiflweIZ5ckT5d-xoEOHumflX3YA

{
  "films":[
    {
      "_id": 8,
      "quantity": 2,
      "size": "S"
    }
  ]   
}