GET http://localhost:5000

###

GET http://localhost:5000/api/auth

###
GET http://localhost:5000/api/watching
###
GET http://localhost:5000/api/favorite

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "tuan",
  "firstname": "tuan",
  "lastname": "nguyen"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nguyentuan200422@gmail.com",
  "password": "tuan"
}

###

GET http://localhost:5000/api/watching
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3NzZhOWMwMWMwY2E3ZTYwNGM2ZjAiLCJpYXQiOjE3MjIzNzM5NDAsImV4cCI6MTcyMjQ2MDM0MH0.0ef6y9D7I7lpm8cWKChlYCqsNEB42wVfQ6UqhtvNVe0

###

PUT http://localhost:5000/api/watching
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjI0NDc1MTUsImV4cCI6MTcyMjUzMzkxNX0.avBAkZnMMwOctP9shtQvl6UjEsM_goGHIZ5jA1ktjpw

{
  "films":   [
    
  ]
}

###

PUT http://localhost:5000/api/watching/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjI0NDc1MTUsImV4cCI6MTcyMjUzMzkxNX0.avBAkZnMMwOctP9shtQvl6UjEsM_goGHIZ5jA1ktjpw

{
  "films":   [
    {
      "_id": 1,
      "quantity": 2,
      "size": "S"
    }
  ]
}

###
DELETE http://localhost:5000/api/watching
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjI0NDc1MTUsImV4cCI6MTcyMjUzMzkxNX0.avBAkZnMMwOctP9shtQvl6UjEsM_goGHIZ5jA1ktjpw

{
  "films":[
    {
      "_id": 1,
      "quantity": 2,
      "size": "S"
    }
  ]  
}



###

GET http://localhost:5000/api/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3NzZhOWMwMWMwY2E3ZTYwNGM2ZjAiLCJpYXQiOjE3MjIzNzM2NjEsImV4cCI6MTcyMjQ2MDA2MX0.ns_0Kc9JRGO2kSsQPbO3VGqR3_vvmp0vrJXmf93LOKM

###

PUT http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjI0MTI4NzIsImV4cCI6MTcyMjQ5OTI3Mn0.7a4SJS77Ik1x3gdq1TSeaxsraibkcyKu8Li0sIwBVTA

{
  "films":   [
    {
      "_id": 8,
      "quantity": 2,
      "size": "S"
    },
    {
      "_id": 7,
      "quantity": 2,
      "size": "S"
    },
    {
      "_id": 5,
      "quantity": 2,
      "size": "S"
    }
  ]
}

###

PUT http://localhost:5000/api/favorite/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjI0MTI4NzIsImV4cCI6MTcyMjQ5OTI3Mn0.7a4SJS77Ik1x3gdq1TSeaxsraibkcyKu8Li0sIwBVTA

{
  "films":[
    {
      "_id": 8,
      "quantity": 2,
      "size": "S"
    }
  ]  
}

###

DELETE http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE3M2IyNDU3NjdhOWFhNjJmMzFjM2EiLCJpYXQiOjE3MjI0MTI4NzIsImV4cCI6MTcyMjQ5OTI3Mn0.7a4SJS77Ik1x3gdq1TSeaxsraibkcyKu8Li0sIwBVTA

{
  "films":[
    {
      "_id": 8,
      "quantity": 2,
      "size": "S"
    }
  ]  
}
